// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6tlxMif8PP5vtnq6C1v31UYJx2yWmbJU',
    appId: '1:291583480134:web:d3fb197e9a70ccf3841547',
    messagingSenderId: '291583480134',
    projectId: 'fir-auth-83b00',
    authDomain: 'fir-auth-83b00.firebaseapp.com',
    storageBucket: 'fir-auth-83b00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr6sCUoJu-77CKj1ylHVE203Y57fydQ4Q',
    appId: '1:291583480134:android:2360924d1a1289ac841547',
    messagingSenderId: '291583480134',
    projectId: 'fir-auth-83b00',
    storageBucket: 'fir-auth-83b00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBYNKHqnR_YXsuOcjvk0N3MA-xHzV0aYY',
    appId: '1:291583480134:ios:765177f85d8dafbf841547',
    messagingSenderId: '291583480134',
    projectId: 'fir-auth-83b00',
    storageBucket: 'fir-auth-83b00.appspot.com',
    iosBundleId: 'com.example.arjunApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBYNKHqnR_YXsuOcjvk0N3MA-xHzV0aYY',
    appId: '1:291583480134:ios:765177f85d8dafbf841547',
    messagingSenderId: '291583480134',
    projectId: 'fir-auth-83b00',
    storageBucket: 'fir-auth-83b00.appspot.com',
    iosBundleId: 'com.example.arjunApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6tlxMif8PP5vtnq6C1v31UYJx2yWmbJU',
    appId: '1:291583480134:web:0f05b3397c2f1a08841547',
    messagingSenderId: '291583480134',
    projectId: 'fir-auth-83b00',
    authDomain: 'fir-auth-83b00.firebaseapp.com',
    storageBucket: 'fir-auth-83b00.appspot.com',
  );

}